rules:
  #####################
  ## RULESET VERSION ##
  #####################

  ruleset-version:
    description: "RESTful API standards ruleset version 1.0.0"
    documentationUrl: "https://github.com/apiglue/talks"
    severity: "hint"
    type: "style"
    given: "$"
    then:
      function: "falsy"

  ####################
  # RULESET METADATA #
  ####################

  RESTFUL-STD-1.1-NAMING-FUNDAMENTALS-API-NAME:
    severity: "error"
    message: "API name must be descriptive and only contain alphanumeric characters"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#11-api-name"
    type: "style"
    given: "$.info.title"
    then:
      - field: "@key"
        function: "pattern"
        functionOptions:
          match: "^[a-zA-Z0-9]+[a-zA-Z0-9 ]*$"

  RESTFUL-STD-2.1.1-CONSISTENCY-FUNDAMENTALS-URI-PARAMS:
    severity: "error"
    message: "URI parameters must be formatted as lower camel case"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#211---uri-parameters"
    given: "$.paths..parameters[?(@.in=='path')].name"
    type: "style"
    then:
      function: "casing"
      functionOptions:
        type: "camel"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-PATH-PARAMS:
    severity: "error"
    message: "Path parameters must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#221---descriptions"
    given: "$.paths..parameters[?(@.in=='path')]"
    type: "style"
    then:
      - field: "description"
        function: "truthy"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-QUERY-PARAMS:
    severity: "error"
    message: "Query parameters must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#221---descriptions"
    given: "$.paths..parameters[?(@.in=='query')]"
    type: "style"
    then:
      - field: "description"
        function: "truthy"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-REQUEST-HEADERS:
    severity: "error"
    message: "Request headers must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#221---descriptions"
    given: "$.paths..parameters[?(@.in=='header')]"
    type: "style"
    then:
      - field: "description"
        function: "truthy"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-RESPONSE-HEADERS:
    severity: "error"
    message: "Response headers must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#221---descriptions"
    given: "$.paths..responses..headers"
    type: "style"
    then:
      - field: "description"
        function: "truthy"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-REQUEST-BODY:
    severity: "error"
    message: "Request body must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#221---descriptions"
    given:
      - "$.paths[*].*.requestBody"
      - "$.components.requestBodies.*"
    type: "style"
    then:
      - field: "description"
        function: "truthy"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-RESPONSE-BODY:
    severity: "error"
    message: "Response body must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#11-api-name"
    given:
      - "$.paths[*]..responses.*"
    type: "style"
    then:
      - field: "description"
        function: "truthy"

  RESTFUL-STD-2.1.2-CONSISTENCY-FUNDAMENTALS-DESCRIPTION-COOKIES:
    severity: "error"
    message: "Cookies must have a description"
    documentationUrl: "https://github.com/apiglue/talks/blob/main/api-design/improving-api-design-with-the-helpstandards.md#11-api-name"
    given: "$.paths..responses..cookies"
    type: "style"
    then:
      - field: "description"
        function: "truthy"
