[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "debugpy>=1.8.16",
    "dotenv>=0.9.9",
    "langchain-openai>=0.3.31",
    "pyyaml>=6.0.2",
    "tzlocal>=5.3.1",
]
